// Bundles server/opsWeekly.js into api/ops-weekly.js (see that file's header).
import { build } from 'esbuild';
await build({
  entryPoints: [new URL('./opsWeekly.js', import.meta.url).pathname],
  outfile: new URL('../api/ops-weekly.js', import.meta.url).pathname,
  bundle: true, platform: 'node', format: 'esm', target: 'node18',
  packages: 'external',
  define: { 'import.meta.env': '{}' },
  banner: { js: '// GENERATED by server/build.mjs from server/opsWeekly.js - do not edit.' },
  logLevel: 'warning',
});
console.log('api/ops-weekly.js built');
