// GENERATED by server/build.mjs from server/opsWeekly.js - do not edit.

// <define:import.meta.env>
var define_import_meta_env_default = {};

// server/opsWeekly.js
import jpeg from "jpeg-js";
import { PNG } from "pngjs";

// src/services/exportImage.js
function sanitizeFilename(name) {
  return (name || "Report").replace(/[\\/*?:"<>|]/g, "_").trim();
}
var imageLoader = null;
function setImageLoader(fn) {
  imageLoader = typeof fn === "function" ? fn : null;
}
function getImageData(url) {
  if (!url) return Promise.resolve(null);
  if (imageLoader) return new Promise((resolve) => resolve(imageLoader(url))).catch(() => null);
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = "Anonymous";
    img.onload = () => {
      const nw = img.naturalWidth || img.width || 800;
      const nh = img.naturalHeight || img.height || 600;
      const maxDim = 800;
      let w = nw;
      let h = nh;
      if (w > maxDim || h > maxDim) {
        if (w > h) {
          h = Math.round(h * maxDim / w);
          w = maxDim;
        } else {
          w = Math.round(w * maxDim / h);
          h = maxDim;
        }
      }
      const canvas = document.createElement("canvas");
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "#FFFFFF";
      ctx.fillRect(0, 0, w, h);
      ctx.drawImage(img, 0, 0, w, h);
      const dataUrl = canvas.toDataURL("image/jpeg", 0.85);
      resolve({
        base64: dataUrl.split(",")[1],
        extension: "jpeg",
        dataUrl,
        aspectRatio: nw / nh,
        width: w,
        height: h
      });
    };
    img.onerror = () => {
      console.warn("Image load error during export:", String(url).substring(0, 40));
      if (String(url).startsWith("data:image")) {
        const parts = String(url).split(",");
        resolve({ base64: parts[1], extension: "jpeg", dataUrl: url, aspectRatio: 1.33, width: 800, height: 600 });
      } else {
        resolve(null);
      }
    };
    img.src = url;
  });
}
var EMU_PER_PX = 9525;
var colWidthToPx = (width) => width * 7 + 5;
var rowPointsToPx = (points) => points * (96 / 72);
var pxToPoints = (px) => px * (72 / 96);
var emu = (px) => Math.round(px * EMU_PER_PX);
function imageAnchor(colIndex, rowIndex, boxX, boxY, boxW, boxH, aspectRatio) {
  const ar = aspectRatio > 0 ? aspectRatio : 4 / 3;
  let drawW = boxW;
  let drawH = drawW / ar;
  if (drawH > boxH) {
    drawH = boxH;
    drawW = drawH * ar;
  }
  const offX = boxX + (boxW - drawW) / 2;
  const offY = boxY + (boxH - drawH) / 2;
  return {
    tl: { nativeCol: colIndex, nativeColOff: emu(offX), nativeRow: rowIndex, nativeRowOff: emu(offY) },
    br: { nativeCol: colIndex, nativeColOff: emu(offX + drawW), nativeRow: rowIndex, nativeRowOff: emu(offY + drawH) },
    drawW,
    drawH
  };
}
function photoGrid(count, cellWidthPx, { maxCols = 3, gap = 3 } = {}) {
  const n = Math.max(1, count);
  const cols = Math.min(n, n > 6 ? maxCols + 1 : maxCols);
  const rows = Math.ceil(n / cols);
  const tileW = (cellWidthPx - gap * (cols + 1)) / cols;
  const tileH = tileW * 0.75;
  return { cols, rows, tileW, tileH, gap, heightPx: rows * (tileH + gap) + gap };
}
function tileBox(index, grid) {
  const r = Math.floor(index / grid.cols);
  const c = index % grid.cols;
  return {
    x: grid.gap + c * (grid.tileW + grid.gap),
    y: grid.gap + r * (grid.tileH + grid.gap),
    w: grid.tileW,
    h: grid.tileH
  };
}
function downloadBlob(blob, fileName) {
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  setTimeout(() => {
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  }, 100);
}
function excelDate(key) {
  if (!key) return null;
  const [y, m, d] = String(key).split("-").map(Number);
  if (!y || !m || !d) return null;
  return new Date(Date.UTC(y, m - 1, d));
}

// src/services/firebase.js
import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  doc,
  getDoc,
  getDocs,
  setDoc,
  deleteDoc,
  writeBatch,
  query,
  orderBy,
  limit,
  serverTimestamp,
  onSnapshot
} from "firebase/firestore";
import {
  getStorage,
  ref,
  uploadBytes,
  getDownloadURL,
  deleteObject,
  listAll
} from "firebase/storage";
var firebaseConfig = {
  apiKey: define_import_meta_env_default.VITE_FIREBASE_API_KEY || "",
  authDomain: define_import_meta_env_default.VITE_FIREBASE_AUTH_DOMAIN || "",
  projectId: define_import_meta_env_default.VITE_FIREBASE_PROJECT_ID || "",
  storageBucket: define_import_meta_env_default.VITE_FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: define_import_meta_env_default.VITE_FIREBASE_MESSAGING_SENDER_ID || "",
  appId: define_import_meta_env_default.VITE_FIREBASE_APP_ID || ""
};
var isFirebaseConfigured = Boolean(
  firebaseConfig.apiKey && firebaseConfig.projectId && firebaseConfig.storageBucket
);
var app = null;
var db = null;
var storage = null;
if (isFirebaseConfigured) {
  app = initializeApp(firebaseConfig);
  db = getFirestore(app);
  storage = getStorage(app);
}

// src/services/previewKind.js
var PREVIEW = Object.freeze({
  IMAGE: "image",
  PDF: "pdf",
  MEDIA: "media",
  // audio / video — the browser plays it
  TEXT: "text",
  // .txt, .log, .json … — the browser shows it
  EML: "eml",
  // internet email (MIME)
  MSG: "msg",
  // Outlook item (OLE compound file)
  DOCX: "docx",
  // Word 2007+
  XLSX: "xlsx",
  // Excel 2007+ (xlsx / xlsm)
  CSV: "csv",
  NONE: "none"
  // download only
});
var BY_EXT = {
  jpg: PREVIEW.IMAGE,
  jpeg: PREVIEW.IMAGE,
  png: PREVIEW.IMAGE,
  gif: PREVIEW.IMAGE,
  webp: PREVIEW.IMAGE,
  bmp: PREVIEW.IMAGE,
  svg: PREVIEW.IMAGE,
  pdf: PREVIEW.PDF,
  mp4: PREVIEW.MEDIA,
  webm: PREVIEW.MEDIA,
  mov: PREVIEW.MEDIA,
  mp3: PREVIEW.MEDIA,
  wav: PREVIEW.MEDIA,
  m4a: PREVIEW.MEDIA,
  ogg: PREVIEW.MEDIA,
  txt: PREVIEW.TEXT,
  log: PREVIEW.TEXT,
  json: PREVIEW.TEXT,
  xml: PREVIEW.TEXT,
  md: PREVIEW.TEXT,
  eml: PREVIEW.EML,
  msg: PREVIEW.MSG,
  docx: PREVIEW.DOCX,
  docm: PREVIEW.DOCX,
  dotx: PREVIEW.DOCX,
  xlsx: PREVIEW.XLSX,
  xlsm: PREVIEW.XLSX,
  xltx: PREVIEW.XLSX,
  csv: PREVIEW.CSV
};
var PREVIEW_LABEL = {
  [PREVIEW.EML]: "Email",
  [PREVIEW.MSG]: "Outlook email",
  [PREVIEW.DOCX]: "Word",
  [PREVIEW.XLSX]: "Excel",
  [PREVIEW.CSV]: "CSV"
};

// src/services/fileAttachments.js
var MAX_FILE_BYTES = 10 * 1024 * 1024;
function attachmentUrl(shareId, key) {
  const base = typeof window === "undefined" ? "https://flash-report-pro.vercel.app/" : window.location.origin + window.location.pathname;
  return `${base}#/file/${shareId}/${key}`;
}

// src/services/opsAuth.js
function sectionLetter(section) {
  const m = /^\s*([A-Za-z])\s*[.)\-:]/.exec(String(section || ""));
  return m ? m[1].toUpperCase() : "";
}

// src/services/opsFindings.js
var OPS_FINDINGS_LABEL = "OPS Findings & Action Tracking";
var OPS_DEFAULT_SECTION = "A. Findings from M&R Team";
var CLOSEOUT_SLOT_BASE = 1e3;
var OPS_COLUMNS = [
  // v3.27.0 order: Remark after Open Date, Corrective Action after Action By.
  { col: "A", key: "no", label: "No" },
  { col: "B", key: "system", label: "System/ Package/ Location" },
  { col: "C", key: "subsystem_no", label: "Subsystem No." },
  { col: "D", key: "description", label: "Finding Description" },
  { col: "E", key: "reference", label: "Reference to PQPOC Spec / Standard" },
  { col: "F", key: "raised_by", label: "Raise By" },
  { col: "G", key: "photos_g", label: "Photo Reference" },
  { col: "H", key: "open_date", label: "Open Date", date: true },
  { col: "I", key: "remark", label: "Remark" },
  { col: "J", key: "pic", label: "PIC" },
  { col: "K", key: "action_by", label: "Action By" },
  { col: "L", key: "action", label: "Corrective Action" },
  { col: "M", key: "status", label: "Status" },
  { col: "N", key: "closeout_date", label: "Close-out Date", date: true },
  { col: "O", key: "closeout_status", label: "Close-out status" },
  { col: "P", key: "updated_date", label: "Updated Date", date: true },
  { col: "Q", key: "photos_o", label: "Close-out references" }
];
var opsColLetter = (key) => OPS_COLUMNS.find((c) => c.key === key)?.col || "";
var OPS_FREE_TEXT_FIELDS = [
  "system",
  "subsystem_no",
  "description",
  "action",
  "reference",
  "raised_by",
  "pic",
  "action_by",
  "remark",
  "closeout_status"
];
var OPS_TEXT_FIELDS = [
  "system",
  "subsystem_no",
  "description",
  "action",
  "reference",
  "raised_by",
  "open_date",
  "pic",
  "action_by",
  "status",
  "closeout_date",
  "remark",
  "closeout_status",
  "updated_date"
];
var OPS_MERGE_FIELDS = [...OPS_TEXT_FIELDS, "section", "report_type"];
var OPS_STATUS = { OPEN: "Open", ONGOING: "On-going", CLOSED: "Closed" };
var OPS_STATUS_OPTIONS = [OPS_STATUS.OPEN, OPS_STATUS.ONGOING, OPS_STATUS.CLOSED];
var OPS_STATUS_STYLE = {
  [OPS_STATUS.OPEN]: {
    label: "Open",
    badge: "bg-rose-600 text-white border-rose-700",
    row: "bg-rose-50/70",
    tile: "text-rose-700",
    argb: "FFDC2626",
    fg: "FFFFFFFF",
    rowArgb: "FFFEF2F2",
    rgb: [220, 38, 38],
    rowRgb: [254, 242, 242]
  },
  [OPS_STATUS.ONGOING]: {
    label: "On-going",
    badge: "bg-amber-400 text-amber-950 border-amber-500",
    row: "bg-amber-50/80",
    tile: "text-amber-700",
    argb: "FFFBBF24",
    fg: "FF451A03",
    rowArgb: "FFFFFBEB",
    rgb: [251, 191, 36],
    rowRgb: [255, 251, 235]
  },
  [OPS_STATUS.CLOSED]: {
    label: "Closed",
    badge: "bg-emerald-600 text-white border-emerald-700",
    row: "bg-emerald-50/70",
    tile: "text-emerald-700",
    argb: "FF059669",
    fg: "FFFFFFFF",
    rowArgb: "FFECFDF5",
    rgb: [5, 150, 105],
    rowRgb: [236, 253, 245]
  }
};
function normalizeOpsStatus(value) {
  const s = String(value ?? "").trim().toLowerCase().replace(/[\s_]+/g, " ");
  if (!s) return OPS_STATUS.OPEN;
  if (/^(closed?|done|complete[d]?|finish(ed)?|resolved)$/.test(s)) return OPS_STATUS.CLOSED;
  if (/^(on ?-? ?going|in ?-? ?progress|progress(ing)?|wip|pending)$/.test(s)) return OPS_STATUS.ONGOING;
  if (/^open(ed)?$/.test(s)) return OPS_STATUS.OPEN;
  if (s.startsWith("close")) return OPS_STATUS.CLOSED;
  if (s.includes("going") || s.includes("progress")) return OPS_STATUS.ONGOING;
  return OPS_STATUS.OPEN;
}
function todayKeyLocal(now = /* @__PURE__ */ new Date()) {
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, "0");
  const d = String(now.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}
function opsDateKey(value) {
  const m = String(value ?? "").match(/^(\d{4})-(\d{2})-(\d{2})/);
  return m ? `${m[1]}-${m[2]}-${m[3]}` : "";
}
var MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function formatOpsDate(value) {
  const k = opsDateKey(value);
  if (!k) return "";
  const [y, m, d] = k.split("-");
  return `${d}-${MONTHS[Number(m) - 1]}-${y.slice(2)}`;
}
var slotColumn = (p, i = 0) => Number(p?.slot_index ?? i) >= CLOSEOUT_SLOT_BASE ? "O" : "G";
function photosOf(item, col) {
  return (item?.photos || []).map((p, i) => p ? { p, i } : null).filter((x) => x && slotColumn(x.p, x.i) === col).sort((a, b) => Number(a.p.slot_index ?? a.i) - Number(b.p.slot_index ?? b.i)).map((x) => x.p);
}
var isFileEntry = (p) => Boolean(p && (p.kind === "file" || !p.url && p.file_ref));
var seq = 0;
function makeOpsId() {
  seq = (seq + 1) % 1e6;
  return `ops_${Date.now().toString(36)}_${seq.toString(36)}_${Math.random().toString(36).slice(2, 6)}`;
}
function normalizeOpsItems(items) {
  if (!Array.isArray(items)) return [];
  let changed = false;
  const out = items.filter(Boolean).map((it) => {
    const fix = {};
    if (!it.id) fix.id = makeOpsId();
    if (typeof it.section !== "string" || !it.section) fix.section = OPS_DEFAULT_SECTION;
    if (!Array.isArray(it.photos)) fix.photos = [];
    const st = normalizeOpsStatus(it.status);
    if (st !== it.status) fix.status = st;
    for (const f of OPS_TEXT_FIELDS) {
      if (it[f] === void 0 || it[f] === null) fix[f] = f === "status" ? st : "";
    }
    if (Object.keys(fix).length) {
      changed = true;
      return { ...it, ...fix };
    }
    return it;
  });
  if (out.length !== items.length) changed = true;
  return changed ? out : items;
}
function opsRowNumbers(items) {
  const out = [];
  const count = /* @__PURE__ */ new Map();
  (items || []).forEach((it, i) => {
    const sec = it?.section || OPS_DEFAULT_SECTION;
    const n = (count.get(sec) || 0) + 1;
    count.set(sec, n);
    out[i] = n;
  });
  return out;
}
function groupOpsSections(items, indices = null) {
  const numbers = opsRowNumbers(items);
  const use = indices || (items || []).map((_, i) => i);
  const groups = [];
  let cur = null;
  for (const i of use) {
    const item = items[i];
    if (!item) continue;
    const section = item.section || OPS_DEFAULT_SECTION;
    if (!cur || cur.section !== section) {
      cur = { section, rows: [] };
      groups.push(cur);
    }
    cur.rows.push({ item, index: i, no: numbers[i] });
  }
  return groups;
}
function opsSections(items) {
  const seen = [];
  for (const it of items || []) {
    const s = it?.section || OPS_DEFAULT_SECTION;
    if (!seen.includes(s)) seen.push(s);
  }
  return seen.length ? seen : [OPS_DEFAULT_SECTION];
}
function opsStats(items) {
  const s = { total: 0, open: 0, ongoing: 0, closed: 0, percentClosed: 0 };
  for (const it of items || []) {
    if (!it) continue;
    s.total += 1;
    const st = normalizeOpsStatus(it.status);
    if (st === OPS_STATUS.CLOSED) s.closed += 1;
    else if (st === OPS_STATUS.ONGOING) s.ongoing += 1;
    else s.open += 1;
  }
  s.percentClosed = s.total ? Math.round(s.closed / s.total * 100) : 0;
  return s;
}
function normalizeSearch(text) {
  return String(text ?? "").normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/đ/g, "d").replace(/Đ/g, "D").toLowerCase().replace(/\s+/g, " ").trim();
}
function opsSectionSummary(items) {
  const order = opsSections(items);
  return order.map((section) => {
    const rows = (items || []).filter((it) => (it?.section || OPS_DEFAULT_SECTION) === section);
    return { section, letter: sectionLetter(section), rows: rows.length, stats: opsStats(rows) };
  });
}
function sectionIndices(items, section) {
  const out = [];
  (items || []).forEach((it, i) => {
    if (!it) return;
    if (!section || (it.section || OPS_DEFAULT_SECTION) === section) out.push(i);
  });
  return out;
}
var DAY = 864e5;
var keyToUtc = (k) => {
  const [y, m, d] = k.split("-").map(Number);
  return Date.UTC(y, m - 1, d);
};
var utcToKey = (t) => new Date(t).toISOString().slice(0, 10);
function opsWeekStart(key) {
  const t = keyToUtc(key);
  const dow = (new Date(t).getUTCDay() + 6) % 7;
  return utcToKey(t - dow * DAY);
}
function closedOn(item) {
  if (normalizeOpsStatus(item?.status) !== OPS_STATUS.CLOSED) return "";
  return opsDateKey(item?.closeout_date) || opsDateKey(item?.updated_date);
}
function opsClosureSeries(items, { today = todayKeyLocal(), maxWeeks = 26 } = {}) {
  const rows = (items || []).filter(Boolean);
  const opened = /* @__PURE__ */ new Map();
  const closed = /* @__PURE__ */ new Map();
  let first = "";
  let undatedOpen = 0;
  let closedNoDate = 0;
  for (const it of rows) {
    const o = opsDateKey(it.open_date);
    if (o) {
      const w = opsWeekStart(o);
      opened.set(w, (opened.get(w) || 0) + 1);
      if (!first || w < first) first = w;
    } else undatedOpen += 1;
    if (normalizeOpsStatus(it.status) === OPS_STATUS.CLOSED) {
      const c = closedOn(it);
      if (c) {
        const w = opsWeekStart(c);
        closed.set(w, (closed.get(w) || 0) + 1);
        if (!first || w < first) first = w;
      } else closedNoDate += 1;
    }
  }
  const nowWeek = opsWeekStart(today);
  if (!first) first = nowWeek;
  const all = [];
  let cumOpened = undatedOpen;
  let cumClosed = closedNoDate;
  for (let t = keyToUtc(first); t <= keyToUtc(nowWeek); t += 7 * DAY) {
    const w = utcToKey(t);
    const o = opened.get(w) || 0;
    const c = closed.get(w) || 0;
    cumOpened += o;
    cumClosed += c;
    all.push({ week: w, label: formatOpsDate(w).slice(0, 6), opened: o, closed: c, cumClosed, backlog: cumOpened - cumClosed, isNow: w === nowWeek });
  }
  return {
    weeks: all.slice(-maxWeeks),
    totals: { total: rows.length, closed: cumClosed, open: rows.length - cumClosed, closedNoDate, undatedOpen }
  };
}
var OPS_NY_CLARIFY = "NY Clarify";
function opsActionByBreakdown(items, status = "") {
  const map = /* @__PURE__ */ new Map();
  let blank = 0;
  for (const it of items || []) {
    if (!it) continue;
    if (status && normalizeOpsStatus(it.status) !== status) continue;
    const raw = String(it.action_by ?? "").replace(/\s+/g, " ").trim();
    if (!raw) {
      blank += 1;
      continue;
    }
    const k = normalizeSearch(raw);
    const e = map.get(k);
    if (e) e.count += 1;
    else map.set(k, { name: raw, count: 1, blank: false });
  }
  const out = [...map.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
  if (blank) out.push({ name: OPS_NY_CLARIFY, count: blank, blank: true });
  return out;
}
var OPS_LEFT_FIELDS = (() => {
  const end = OPS_COLUMNS.findIndex((c) => c.key === "remark");
  return OPS_COLUMNS.slice(1, end + 1).map((c) => c.key).filter((k) => k !== "photos_g");
})();

// src/services/opsFindingsExport.js
var NAVY = "FF1F3A5F";
var NAVY_RGB = [31, 58, 95];
function fileBase(report) {
  const title = sanitizeFilename(report?.title || OPS_FINDINGS_LABEL);
  return `${title}_${todayKeyLocal().replace(/-/g, "")}`;
}
function scopeOf(report, view) {
  const items = report?.items || [];
  const indices = view?.active && Array.isArray(view.indices) ? view.indices : null;
  const groups = groupOpsSections(items, indices);
  const rows = groups.flatMap((g) => g.rows.map((r) => r.item));
  return { items, groups, rows, label: indices ? view.label || "Filtered" : "" };
}
function linesFor(text, widthUnits) {
  const s = String(text || "");
  if (!s) return 1;
  const perLine = Math.max(8, Math.floor(widthUnits * 1.1));
  return s.split("\n").reduce((n, part) => n + Math.max(1, Math.ceil(part.length / perLine)), 0);
}
var images = (item, col) => photosOf(item, col).filter((p) => p && p.url && !isFileEntry(p));
var files = (item, col) => photosOf(item, col).filter((p) => isFileEntry(p) && p.file_ref);
var OPS_KEYS = OPS_COLUMNS.map((c) => c.key);
var colIdx = (key) => OPS_KEYS.indexOf(key);
var XL_WIDTH_OF = {
  no: 5,
  system: 20,
  subsystem_no: 14,
  description: 42,
  action: 32,
  reference: 18,
  raised_by: 11,
  photos_g: 34,
  open_date: 11,
  pic: 16,
  action_by: 16,
  status: 11,
  closeout_date: 11,
  remark: 36,
  closeout_status: 26,
  updated_date: 11,
  photos_o: 28
};
var XL_WIDTHS = OPS_KEYS.map((k) => XL_WIDTH_OF[k] || 14);
var COL_G = colIdx("photos_g");
var COL_O = colIdx("photos_o");
var LAST_COL = XL_WIDTHS.length;
var LAST_LETTER = opsColLetter("photos_o");
var STATUS_LETTER = opsColLetter("status");
var HEADER_ROW = 9;
async function writeFindingsSheet(wb, report, { groups, rows, label, sheetName, subtitle }) {
  const stats = opsStats(rows);
  const shareId = report.share_id || report.cloud_code || "";
  const ws = wb.addWorksheet(sheetName, {
    views: [{ state: "frozen", ySplit: HEADER_ROW, xSplit: 0 }],
    pageSetup: { orientation: "landscape", paperSize: 8, fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  ws.columns = XL_WIDTHS.map((width) => ({ width }));
  const thin = (argb = "FFBFC7D5") => ({
    top: { style: "thin", color: { argb } },
    left: { style: "thin", color: { argb } },
    bottom: { style: "thin", color: { argb } },
    right: { style: "thin", color: { argb } }
  });
  const font = (o = {}) => ({ name: "Arial", size: 9.5, color: { argb: "FF1E293B" }, ...o });
  ws.mergeCells("A1:B1");
  ws.mergeCells("A2:B2");
  ws.getCell("A1").value = "Updated by:";
  ws.getCell("A2").value = "Updated date:";
  ["A1", "A2"].forEach((a) => {
    ws.getCell(a).font = font({ bold: true });
  });
  ws.getCell("C1").value = report.system_tag || "";
  ws.getCell("C1").font = font({ bold: true, color: { argb: NAVY } });
  const upd = opsDateKey(report.inspection_date);
  if (upd) {
    ws.getCell("C2").value = excelDate(upd);
    ws.getCell("C2").numFmt = "d-mmm-yy";
  }
  ws.getCell("C2").font = font({ bold: true, color: { argb: NAVY } });
  ws.getCell("C2").alignment = { horizontal: "left" };
  ws.mergeCells(`A4:${LAST_LETTER}4`);
  ws.getCell("A4").value = report.title || OPS_FINDINGS_LABEL;
  ws.getCell("A4").font = { name: "Arial", size: 16, bold: true, color: { argb: NAVY } };
  ws.getCell("A4").alignment = { horizontal: "center", vertical: "middle" };
  ws.getRow(4).height = 26;
  ws.mergeCells(`A5:${LAST_LETTER}5`);
  ws.getCell("A5").value = subtitle || report.location || "";
  ws.getCell("A5").font = { name: "Arial", size: 12, bold: true, color: { argb: "FF334155" } };
  ws.getCell("A5").alignment = { horizontal: "center" };
  const firstData = HEADER_ROW + 1;
  let lastData = firstData;
  const sumHead = ["Total", "Open", "On-going", "Closed", "Closed %"];
  sumHead.forEach((h, i) => {
    const c = ws.getCell(6, 3 + i);
    c.value = h;
    c.font = font({ bold: true, color: { argb: "FFFFFFFF" }, size: 9 });
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: i === 1 ? OPS_STATUS_STYLE.Open.argb : i === 2 ? "FFD97706" : i === 3 ? OPS_STATUS_STYLE.Closed.argb : NAVY } };
    c.alignment = { horizontal: "center" };
    c.border = thin();
  });
  ws.getCell("B6").value = "Summary";
  ws.getCell("B6").font = font({ bold: true });
  ws.getCell("B6").alignment = { horizontal: "right" };
  if (label) {
    ws.mergeCells(`A8:${LAST_LETTER}8`);
    ws.getCell("A8").value = `${label} \u2014 ${rows.length} finding(s)`;
    ws.getCell("A8").font = font({ italic: true, color: { argb: "FF9A3412" } });
  }
  const head = ws.getRow(HEADER_ROW);
  OPS_COLUMNS.forEach((c, i) => {
    const cell = head.getCell(i + 1);
    cell.value = c.label;
    cell.font = font({ bold: true, color: { argb: "FFFFFFFF" }, size: 10 });
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
    cell.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
    cell.border = thin(NAVY);
  });
  head.height = 32;
  const gPx = colWidthToPx(XL_WIDTHS[COL_G]);
  const oPx = colWidthToPx(XL_WIDTHS[COL_O]);
  let r = firstData;
  for (const g of groups) {
    ws.mergeCells(r, 1, r, LAST_COL);
    const sc = ws.getCell(r, 1);
    sc.value = g.section;
    sc.font = font({ bold: true, size: 11, color: { argb: "FFFFFFFF" } });
    sc.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF334155" } };
    sc.alignment = { vertical: "middle" };
    ws.getRow(r).height = 20;
    r += 1;
    for (const { item, no } of g.rows) {
      const st = normalizeOpsStatus(item.status);
      const style = OPS_STATUS_STYLE[st];
      const gi = images(item, "G");
      const oi = images(item, "O");
      const of = files(item, "O");
      const textLines = Math.max(
        ...OPS_FREE_TEXT_FIELDS.map((k) => linesFor(item[k], XL_WIDTHS[colIdx(k)])),
        1
      );
      let height = Math.max(30, textLines * 12.5 + 8);
      const gGrid = gi.length ? photoGrid(gi.length, gPx, { maxCols: 2 }) : null;
      const oGrid = oi.length ? photoGrid(oi.length, oPx, { maxCols: 2 }) : null;
      const fileTopPx = of.length ? of.length * 15 + 4 : 0;
      if (gGrid) height = Math.max(height, pxToPoints(gGrid.heightPx) + 4);
      if (oGrid || of.length) height = Math.max(height, pxToPoints(fileTopPx + (oGrid ? oGrid.heightPx : 0)) + 4);
      height = Math.min(height, 409);
      const row = ws.getRow(r);
      row.height = height;
      const set = (col, value, extra = {}) => {
        const c = ws.getCell(r, col);
        c.value = value;
        c.font = font(extra.font || {});
        c.alignment = { vertical: "top", wrapText: true, ...extra.alignment || {} };
        c.border = thin();
        if (style.rowArgb) c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: style.rowArgb } };
        return c;
      };
      const date = (col, v) => {
        const k = opsDateKey(v);
        const c = set(col, k ? excelDate(k) : "", { alignment: { horizontal: "center" } });
        if (k) c.numFmt = "d-mmm-yy";
      };
      const center = { alignment: { horizontal: "center" } };
      let oc = null;
      OPS_COLUMNS.forEach((c, i) => {
        const col = i + 1;
        if (c.date) {
          date(col, item[c.key]);
          return;
        }
        switch (c.key) {
          case "no":
            set(col, no, { font: { bold: true }, alignment: { horizontal: "center" } });
            break;
          case "system":
            set(col, item.system || "", { font: { bold: true } });
            break;
          case "photos_g":
            set(col, "");
            break;
          case "photos_o":
            oc = set(col, "");
            break;
          case "status": {
            const sc2 = set(col, st, { font: { bold: true, color: { argb: style.fg } }, alignment: { horizontal: "center", vertical: "middle" } });
            sc2.fill = { type: "pattern", pattern: "solid", fgColor: { argb: style.argb } };
            break;
          }
          case "subsystem_no":
          case "raised_by":
          case "pic":
          case "action_by":
            set(col, item[c.key] || "", center);
            break;
          default:
            set(col, item[c.key] || "");
        }
      });
      if (of.length) {
        const names = of.map((f2) => f2.filename || "file").join("\n");
        if (shareId) {
          oc.value = { text: names, hyperlink: attachmentUrl(shareId, of[0].file_ref) };
          oc.font = font({ size: 9, underline: true, color: { argb: "FF0563C1" } });
        } else {
          oc.value = names;
          oc.font = font({ size: 9 });
        }
      }
      const cellHpx = rowPointsToPx(height);
      const place = async (list, grid, colIndex, yOffset) => {
        for (const [i, p] of list.entries()) {
          const img = await getImageData(p.url);
          if (!img?.base64) continue;
          try {
            const id = wb.addImage({ base64: img.base64, extension: "jpeg" });
            const box = tileBox(i, grid);
            const top = yOffset + box.y;
            const h = Math.min(box.h, Math.max(8, cellHpx - top - grid.gap));
            if (h <= 8) continue;
            const { tl, br } = imageAnchor(colIndex, r - 1, box.x, top, box.w, h, img.aspectRatio);
            ws.addImage(id, { tl, br, editAs: "oneCell" });
          } catch (e) {
            console.error("OPS export: could not place an image", e);
          }
        }
      };
      if (gGrid) await place(gi, gGrid, COL_G, 0);
      if (oGrid) await place(oi, oGrid, COL_O, fileTopPx);
      lastData = r;
      r += 1;
    }
  }
  const J = `${STATUS_LETTER}${firstData}:${STATUS_LETTER}${Math.max(firstData, lastData)}`;
  const f = (formula, result) => ({ formula, result });
  ws.getCell(7, 4).value = f(`COUNTIF(${J},"Open")`, stats.open);
  ws.getCell(7, 5).value = f(`COUNTIF(${J},"On-going")`, stats.ongoing);
  ws.getCell(7, 6).value = f(`COUNTIF(${J},"Closed")`, stats.closed);
  ws.getCell(7, 3).value = f("D7+E7+F7", stats.total);
  ws.getCell(7, 7).value = f("IF(C7=0,0,F7/C7)", stats.total ? stats.closed / stats.total : 0);
  ws.getCell(7, 7).numFmt = "0%";
  for (let c = 3; c <= 7; c += 1) {
    const cell = ws.getCell(7, c);
    cell.font = font({ bold: true, size: 11 });
    cell.alignment = { horizontal: "center" };
    cell.border = thin();
  }
  ws.autoFilter = { from: { row: HEADER_ROW, column: 1 }, to: { row: Math.max(HEADER_ROW, lastData), column: LAST_COL } };
  for (let rr = firstData; rr <= lastData; rr += 1) {
    ws.getCell(rr, OPS_COLUMNS.findIndex((c) => c.key === "status") + 1).dataValidation = {
      type: "list",
      allowBlank: true,
      formulae: [`"${OPS_STATUS_OPTIONS.join(",")}"`]
    };
  }
  return { sheetName, firstData, lastData };
}
function sheetNameFor(section, used) {
  const L = sectionLetter(section);
  let base = (L ? `Section ${L}` : String(section || "Section")).replace(/[[\]:*?/\\]/g, " ").slice(0, 31).trim() || "Section";
  let name = base;
  let n = 2;
  while (used.has(name.toLowerCase())) name = `${base.slice(0, 27)} (${n++})`;
  used.add(name.toLowerCase());
  return name;
}
async function exportOpsExcel(report, view = null, opts = {}) {
  if (!report) throw new Error("No report data provided");
  const { default: ExcelJS } = await import("exceljs");
  const wb = new ExcelJS.Workbook();
  wb.creator = "Flash Report Pro";
  wb.created = /* @__PURE__ */ new Date();
  const items = report.items || [];
  const used = /* @__PURE__ */ new Set();
  if (view?.section) {
    const { groups, rows } = scopeOf(report, view);
    const filterOn = view.filter && Object.values(view.filter).some(Boolean);
    await writeFindingsSheet(wb, report, {
      groups,
      rows,
      label: filterOn ? `Filtered \u2014 ${view.label}` : "",
      sheetName: sheetNameFor(view.section, used),
      subtitle: view.section
    });
    return saveWorkbook(wb, `${fileBase(report)}_${sectionLetter(view.section) || "section"}`, opts);
  }
  const sum = wb.addWorksheet("Summary", {
    pageSetup: { orientation: "landscape", paperSize: 9, fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
  });
  const sections = opsSectionSummary(items);
  const refs = [];
  for (const s of sections) {
    const groups = groupOpsSections(items, sectionIndices(items, s.section));
    const rows = groups.flatMap((g) => g.rows.map((r) => r.item));
    const at = await writeFindingsSheet(wb, report, {
      groups,
      rows,
      label: "",
      sheetName: sheetNameFor(s.section, used),
      subtitle: s.section
    });
    refs.push({ ...s, ...at });
  }
  await writeSummarySheet(wb, sum, report, refs, items);
  return saveWorkbook(wb, fileBase(report), opts);
}
async function saveWorkbook(wb, name, opts = {}) {
  const buffer = await wb.xlsx.writeBuffer();
  if (opts.returnBuffer) return { buffer, fileName: `${opts.fileName || name}.xlsx` };
  downloadBlob(
    new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }),
    `${name}.xlsx`
  );
}
async function writeSummarySheet(wb, ws, report, refs, items) {
  const font = (o = {}) => ({ name: "Arial", size: 10, color: { argb: "FF1E293B" }, ...o });
  const border = {
    top: { style: "thin", color: { argb: "FFBFC7D5" } },
    left: { style: "thin", color: { argb: "FFBFC7D5" } },
    bottom: { style: "thin", color: { argb: "FFBFC7D5" } },
    right: { style: "thin", color: { argb: "FFBFC7D5" } }
  };
  ws.columns = [{ width: 44 }, { width: 11 }, { width: 11 }, { width: 11 }, { width: 11 }, { width: 12 }, { width: 22 }];
  ws.mergeCells("A1:G1");
  ws.getCell("A1").value = report.title || OPS_FINDINGS_LABEL;
  ws.getCell("A1").font = { name: "Arial", size: 16, bold: true, color: { argb: NAVY } };
  ws.getRow(1).height = 26;
  ws.mergeCells("A2:G2");
  ws.getCell("A2").value = [
    report.location,
    report.system_tag ? `Updated by: ${report.system_tag}` : "",
    opsDateKey(report.inspection_date) ? `Updated date: ${formatOpsDate(report.inspection_date)}` : "",
    `Exported ${formatOpsDate(todayKeyLocal())}`
  ].filter(Boolean).join("   |   ");
  ws.getCell("A2").font = font({ color: { argb: "FF51607A" } });
  const HEAD = 4;
  ["Section", "Total", "Open", "On-going", "Closed", "Closed %", "Sheet"].forEach((h, i) => {
    const c = ws.getCell(HEAD, i + 1);
    c.value = h;
    c.font = font({ bold: true, color: { argb: "FFFFFFFF" } });
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: NAVY } };
    c.alignment = { horizontal: i ? "center" : "left", vertical: "middle" };
    c.border = border;
  });
  ws.getRow(HEAD).height = 22;
  const f = (formula, result) => ({ formula, result });
  let r = HEAD + 1;
  for (const s of refs) {
    const J = `'${s.sheetName}'!$${STATUS_LETTER}$${s.firstData}:$${STATUS_LETTER}$${Math.max(s.firstData, s.lastData)}`;
    ws.getCell(r, 1).value = s.section;
    ws.getCell(r, 3).value = f(`COUNTIF(${J},"Open")`, s.stats.open);
    ws.getCell(r, 4).value = f(`COUNTIF(${J},"On-going")`, s.stats.ongoing);
    ws.getCell(r, 5).value = f(`COUNTIF(${J},"Closed")`, s.stats.closed);
    ws.getCell(r, 2).value = f(`C${r}+D${r}+E${r}`, s.stats.total);
    ws.getCell(r, 6).value = f(`IF(B${r}=0,0,E${r}/B${r})`, s.stats.total ? s.stats.closed / s.stats.total : 0);
    ws.getCell(r, 7).value = { text: s.sheetName, hyperlink: `#'${s.sheetName}'!A1` };
    r += 1;
  }
  const first = HEAD + 1;
  const last = r - 1;
  const all = opsStats(items);
  ws.getCell(r, 1).value = "Total";
  ws.getCell(r, 2).value = f(`SUM(B${first}:B${last})`, all.total);
  ws.getCell(r, 3).value = f(`SUM(C${first}:C${last})`, all.open);
  ws.getCell(r, 4).value = f(`SUM(D${first}:D${last})`, all.ongoing);
  ws.getCell(r, 5).value = f(`SUM(E${first}:E${last})`, all.closed);
  ws.getCell(r, 6).value = f(`IF(B${r}=0,0,E${r}/B${r})`, all.total ? all.closed / all.total : 0);
  for (let rr = first; rr <= r; rr += 1) {
    const total = rr === r;
    for (let c = 1; c <= 7; c += 1) {
      const cell = ws.getCell(rr, c);
      cell.border = border;
      cell.alignment = { horizontal: c === 1 ? "left" : "center", vertical: "middle" };
      const colour = c === 3 ? "FFB91C1C" : c === 4 ? "FFB45309" : c === 5 ? "FF047857" : c === 7 ? "FF0563C1" : "FF1E293B";
      cell.font = font({ bold: total || c > 1, color: { argb: colour }, underline: c === 7 });
      if (total) cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF1F5F9" } };
    }
    ws.getCell(rr, 6).numFmt = "0%";
    ws.getRow(rr).height = 20;
  }
  try {
    const png = closureChartPng(items, { width: 980, height: 330 });
    if (png) {
      const top = r + 2;
      ws.getCell(top, 1).value = "FINDINGS CLOSED OVER TIME (BY WEEK)";
      ws.getCell(top, 1).font = font({ bold: true, color: { argb: NAVY } });
      const id = wb.addImage({ base64: png.split(",")[1], extension: "png" });
      ws.addImage(id, { tl: { col: 0.05, row: top + 0.2 }, ext: { width: 980, height: 330 }, editAs: "oneCell" });
    }
  } catch (e) {
    console.error("OPS summary chart not drawn:", e);
  }
}
function closureChartPng(items, { width = 980, height = 330 } = {}) {
  if (typeof document === "undefined") return "";
  const { weeks } = opsClosureSeries(items, { maxWeeks: 30 });
  const cv = document.createElement("canvas");
  const k = 2;
  cv.width = width * k;
  cv.height = height * k;
  const ctx = cv.getContext("2d");
  ctx.scale(k, k);
  ctx.fillStyle = "#FFFFFF";
  ctx.fillRect(0, 0, width, height);
  const pad = { l: 40, r: 44, t: 26, b: 44 };
  const iw = width - pad.l - pad.r;
  const ih = height - pad.t - pad.b;
  const n = Math.max(1, weeks.length);
  const slot = iw / n;
  const barW = Math.max(3, Math.min(16, slot * 0.32));
  const maxBar = Math.max(1, ...weeks.map((w) => Math.max(w.opened, w.closed)));
  const maxLine = Math.max(1, ...weeks.map((w) => Math.max(w.cumClosed, w.backlog)));
  const yb = (v) => pad.t + ih - v / maxBar * ih;
  const yl = (v) => pad.t + ih - v / maxLine * ih;
  const xc = (i) => pad.l + slot * i + slot / 2;
  ctx.font = "11px Arial";
  for (const fr of [0, 0.25, 0.5, 0.75, 1]) {
    const y = pad.t + ih * (1 - fr);
    ctx.strokeStyle = "#E2E8F0";
    ctx.beginPath();
    ctx.moveTo(pad.l, y);
    ctx.lineTo(width - pad.r, y);
    ctx.stroke();
    ctx.fillStyle = "#64748B";
    ctx.textAlign = "right";
    ctx.fillText(String(Math.round(maxBar * fr)), pad.l - 5, y + 4);
    ctx.textAlign = "left";
    ctx.fillText(String(Math.round(maxLine * fr)), width - pad.r + 5, y + 4);
  }
  const every = Math.max(1, Math.ceil(n / Math.max(4, Math.floor(iw / 58))));
  weeks.forEach((w, i) => {
    if (w.isNow) {
      ctx.fillStyle = "#EEF2FF";
      ctx.fillRect(pad.l + slot * i, pad.t, slot, ih);
    }
    ctx.fillStyle = "#CBD5E1";
    ctx.fillRect(xc(i) - barW - 1, yb(w.opened), barW, pad.t + ih - yb(w.opened));
    ctx.fillStyle = "#059669";
    ctx.fillRect(xc(i) + 1, yb(w.closed), barW, pad.t + ih - yb(w.closed));
    if (w.closed) {
      ctx.fillStyle = "#059669";
      ctx.textAlign = "center";
      ctx.fillText(String(w.closed), xc(i) + 1 + barW / 2, yb(w.closed) - 3);
    }
    if (i % every === 0 || w.isNow) {
      ctx.fillStyle = w.isNow ? "#4338CA" : "#64748B";
      ctx.textAlign = "center";
      ctx.fillText(w.isNow ? "NOW" : w.label, xc(i), height - pad.b + 16);
    }
  });
  const drawLine = (key, colour) => {
    ctx.strokeStyle = colour;
    ctx.lineWidth = 2.2;
    ctx.beginPath();
    weeks.forEach((w, i) => {
      if (i) ctx.lineTo(xc(i), yl(w[key]));
      else ctx.moveTo(xc(i), yl(w[key]));
    });
    ctx.stroke();
    ctx.lineWidth = 1;
    const lastW = weeks[weeks.length - 1];
    if (lastW) {
      ctx.fillStyle = colour;
      ctx.textAlign = "center";
      ctx.font = "bold 11px Arial";
      ctx.fillText(String(lastW[key]), xc(n - 1), yl(lastW[key]) - 7);
      ctx.font = "11px Arial";
    }
  };
  drawLine("backlog", "#DC2626");
  drawLine("cumClosed", "#047857");
  const legend = [["#CBD5E1", "Opened in week", "bar"], ["#059669", "Closed in week", "bar"], ["#047857", "Total closed (right)", "line"], ["#DC2626", "Still open (right)", "line"]];
  let lx = pad.l;
  const ly = height - 12;
  ctx.textAlign = "left";
  for (const [c, t, kind] of legend) {
    ctx.fillStyle = c;
    if (kind === "bar") ctx.fillRect(lx, ly - 8, 12, 9);
    else ctx.fillRect(lx, ly - 4, 14, 2.5);
    ctx.fillStyle = "#334155";
    ctx.fillText(t, lx + 17, ly);
    lx += 34 + ctx.measureText(t).width;
  }
  return cv.toDataURL("image/png");
}
var PDF_W_OF = {
  no: 22,
  system: 70,
  subsystem_no: 50,
  description: 112,
  action: 100,
  reference: 50,
  raised_by: 44,
  photos_g: 136,
  open_date: 44,
  pic: 60,
  action_by: 56,
  status: 46,
  closeout_date: 44,
  remark: 96,
  closeout_status: 72,
  updated_date: 44,
  photos_o: 96
};
var PDF_W = OPS_KEYS.map((k) => PDF_W_OF[k] || 44);
var P_G = colIdx("photos_g");
var P_O = colIdx("photos_o");
var P_STATUS = colIdx("status");
var PDF_CENTER = new Set(OPS_COLUMNS.map((c, i) => c.key === "no" || c.key === "status" || c.key === "subsystem_no" || c.date ? i : -1).filter((i) => i >= 0));
async function exportOpsPdf(report, view = null, opts = {}) {
  if (!report) throw new Error("No report data provided");
  const [jspdfMod, autoTableMod] = await Promise.all([import("jspdf"), import("jspdf-autotable")]);
  const jsPDF = jspdfMod.jsPDF || jspdfMod.default?.jsPDF || jspdfMod.default;
  if (typeof jsPDF.API.autoTable !== "function" && autoTableMod.applyPlugin) autoTableMod.applyPlugin(jsPDF);
  const { groups, rows, label } = scopeOf(report, view);
  const stats = opsStats(rows);
  const shareId = report.share_id || report.cloud_code || "";
  const doc2 = new jsPDF({ orientation: "landscape", unit: "pt", format: "a3" });
  const pageW = doc2.internal.pageSize.getWidth();
  const pageH = doc2.internal.pageSize.getHeight();
  doc2.setFont("Helvetica", "bold");
  doc2.setFontSize(15);
  doc2.setTextColor(...NAVY_RGB);
  doc2.text(report.title || OPS_FINDINGS_LABEL, 24, 34);
  doc2.setFontSize(10.5);
  doc2.setTextColor(51, 65, 85);
  const sub = view?.section || report.location;
  if (sub) doc2.text(sub, 24, 50);
  doc2.setFont("Helvetica", "normal");
  doc2.setFontSize(8.5);
  doc2.setTextColor(81, 96, 122);
  const who = [
    report.system_tag ? `Updated by: ${report.system_tag}` : "",
    opsDateKey(report.inspection_date) ? `Updated date: ${formatOpsDate(report.inspection_date)}` : "",
    `Exported ${formatOpsDate(todayKeyLocal())}`
  ].filter(Boolean).join("   |   ");
  doc2.text(who, 24, 64);
  let x = 24;
  const y = 72;
  const chip = (text, rgb, fg = [255, 255, 255]) => {
    doc2.setFont("Helvetica", "bold");
    doc2.setFontSize(8.5);
    const w = doc2.getTextWidth(text) + 14;
    doc2.setFillColor(...rgb);
    doc2.roundedRect(x, y, w, 15, 3, 3, "F");
    doc2.setTextColor(...fg);
    doc2.text(text, x + 7, y + 10.5);
    x += w + 6;
  };
  chip(`Total ${stats.total}`, NAVY_RGB);
  chip(`Open ${stats.open}`, OPS_STATUS_STYLE.Open.rgb);
  chip(`On-going ${stats.ongoing}`, OPS_STATUS_STYLE["On-going"].rgb, [69, 26, 3]);
  chip(`Closed ${stats.closed}`, OPS_STATUS_STYLE.Closed.rgb);
  chip(`Closed ${stats.percentClosed}%`, [71, 85, 105]);
  if (label) {
    doc2.setFont("Helvetica", "italic");
    doc2.setFontSize(8.5);
    doc2.setTextColor(154, 52, 18);
    doc2.text(`${label} \u2014 ${rows.length} finding(s)`, x + 6, y + 10.5);
  }
  let tableStart = 94;
  if (!view?.section) {
    const secs = opsSectionSummary(report.items || []);
    const all = opsStats(report.items || []);
    doc2.autoTable({
      startY: 96,
      margin: { left: 24, right: 24 },
      tableWidth: 640,
      head: [["Section", "Total", "Open", "On-going", "Closed", "% closed"]],
      body: [
        ...secs.map((sx) => [sx.section, sx.stats.total, sx.stats.open, sx.stats.ongoing, sx.stats.closed, `${sx.stats.percentClosed}%`]),
        ["Total", all.total, all.open, all.ongoing, all.closed, `${all.percentClosed}%`]
      ],
      theme: "grid",
      styles: { font: "Helvetica", fontSize: 9, cellPadding: 4, lineColor: [203, 213, 225], lineWidth: 0.5 },
      headStyles: { fillColor: NAVY_RGB, textColor: [255, 255, 255], fontStyle: "bold" },
      columnStyles: { 0: { cellWidth: 300 }, 1: { halign: "center" }, 2: { halign: "center", textColor: [185, 28, 28] }, 3: { halign: "center", textColor: [180, 83, 9] }, 4: { halign: "center", textColor: [4, 120, 87] }, 5: { halign: "center" } },
      didParseCell: (d) => {
        if (d.section === "body" && d.row.index === secs.length) {
          d.cell.styles.fontStyle = "bold";
          d.cell.styles.fillColor = [241, 245, 249];
        }
      }
    });
    try {
      const png = closureChartPng(report.items || [], { width: 980, height: 330 });
      const top = (doc2.lastAutoTable?.finalY || 200) + 24;
      doc2.setFont("Helvetica", "bold");
      doc2.setFontSize(10);
      doc2.setTextColor(...NAVY_RGB);
      doc2.text("Findings closed over time (by week)", 24, top);
      if (png) doc2.addImage(png, "PNG", 24, top + 8, 980 * 0.8, 330 * 0.8);
    } catch (e) {
      console.error("OPS PDF chart:", e);
    }
    doc2.addPage();
    tableStart = 30;
  }
  const body = [];
  const meta = [];
  for (const g of groups) {
    body.push([{ content: g.section, colSpan: OPS_COLUMNS.length, styles: { fillColor: [51, 65, 85], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 } }]);
    meta.push({ section: true });
    for (const { item, no } of g.rows) {
      const st = normalizeOpsStatus(item.status);
      const gImgs = [];
      for (const p of images(item, "G")) {
        const im = await getImageData(p.url);
        if (im) gImgs.push(im);
      }
      const oImgs = [];
      for (const p of images(item, "O")) {
        const im = await getImageData(p.url);
        if (im) oImgs.push(im);
      }
      body.push(OPS_COLUMNS.map((c) => {
        if (c.key === "no") return String(no);
        if (c.key === "status") return st;
        if (c.key === "photos_g" || c.key === "photos_o") return "";
        if (c.date) return formatOpsDate(item[c.key]);
        return item[c.key] || "";
      }));
      meta.push({ item, gImgs, oImgs, oFiles: files(item, "O"), style: OPS_STATUS_STYLE[st] });
    }
  }
  const gridFor = (n, w) => photoGrid(n, w - 6, { maxCols: 2 });
  doc2.autoTable({
    startY: tableStart,
    margin: { left: 24, right: 24, bottom: 30 },
    head: [OPS_COLUMNS.map((c) => c.label)],
    body,
    theme: "grid",
    rowPageBreak: "avoid",
    showHead: "everyPage",
    styles: {
      font: "Helvetica",
      fontSize: 6.8,
      cellPadding: 2.5,
      valign: "top",
      lineColor: [203, 213, 225],
      lineWidth: 0.5,
      overflow: "linebreak",
      textColor: [30, 41, 59]
    },
    headStyles: { fillColor: NAVY_RGB, textColor: [255, 255, 255], fontStyle: "bold", halign: "center", valign: "middle", fontSize: 7 },
    columnStyles: Object.fromEntries(PDF_W.map((w, i) => [i, { cellWidth: w }])),
    didParseCell: (data) => {
      if (data.section !== "body") return;
      const m = meta[data.row.index];
      if (!m || m.section) return;
      const ci = data.column.index;
      if (m.style?.rowRgb) data.cell.styles.fillColor = m.style.rowRgb;
      if (PDF_CENTER.has(ci)) data.cell.styles.halign = "center";
      if (ci === 0 || ci === 1) data.cell.styles.fontStyle = "bold";
      if (ci === P_STATUS) {
        data.cell.styles.fillColor = m.style.rgb;
        data.cell.styles.textColor = m.style === OPS_STATUS_STYLE["On-going"] ? [69, 26, 3] : [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.valign = "middle";
      }
      if (ci === P_G && m.gImgs.length) {
        data.cell.styles.minCellHeight = Math.min(300, gridFor(m.gImgs.length, PDF_W[P_G]).heightPx + 6);
      }
      if (ci === P_O && (m.oImgs.length || m.oFiles.length)) {
        const top = m.oFiles.length * 9 + (m.oFiles.length ? 3 : 0);
        const gh = m.oImgs.length ? gridFor(m.oImgs.length, PDF_W[P_O]).heightPx : 0;
        data.cell.styles.minCellHeight = Math.min(300, top + gh + 6);
      }
    },
    didDrawCell: (data) => {
      if (data.section !== "body") return;
      const m = meta[data.row.index];
      if (!m || m.section) return;
      const ci = data.column.index;
      if (ci !== P_G && ci !== P_O) return;
      const cell = data.cell;
      let top = cell.y + 3;
      if (ci === P_O && m.oFiles.length) {
        doc2.setFont("Helvetica", "normal");
        doc2.setFontSize(6.5);
        doc2.setTextColor(5, 99, 193);
        for (const fl of m.oFiles) {
          const name = String(fl.filename || "file");
          const t = doc2.splitTextToSize(name, cell.width - 6)[0];
          if (shareId) doc2.textWithLink(t, cell.x + 3, top + 6, { url: attachmentUrl(shareId, fl.file_ref) });
          else doc2.text(t, cell.x + 3, top + 6);
          top += 9;
        }
        top += 3;
      }
      const list = ci === P_G ? m.gImgs : m.oImgs;
      if (!list.length) return;
      const grid = gridFor(list.length, cell.width);
      list.forEach((img, i) => {
        const box = tileBox(i, grid);
        const ar = img.aspectRatio || 4 / 3;
        let w = box.w;
        let h = w / ar;
        if (h > box.h) {
          h = box.h;
          w = h * ar;
        }
        const ix = cell.x + 3 + box.x + (box.w - w) / 2;
        const iy = top + box.y + (box.h - h) / 2;
        if (iy + h > cell.y + cell.height) return;
        try {
          doc2.addImage(img.dataUrl, "JPEG", ix, iy, w, h, void 0, "FAST");
        } catch (e) {
          console.error("OPS PDF image:", e);
        }
      });
    },
    didDrawPage: () => {
      doc2.setFont("Helvetica", "normal");
      doc2.setFontSize(7.5);
      doc2.setTextColor(132, 148, 172);
      doc2.text(`Block B - EPC#1  |  ${report.title || OPS_FINDINGS_LABEL}`, 24, pageH - 14);
      doc2.text(`Page ${doc2.internal.getNumberOfPages()}`, pageW - 24, pageH - 14, { align: "right" });
    }
  });
  if (opts.returnBuffer) return { buffer: doc2.output("arraybuffer"), fileName: `${opts.fileName || fileBase(report)}.pdf` };
  doc2.save(`${fileBase(report)}.pdf`);
}

// server/opsWeekly.js
var MAX_PX = 520;
var QUALITY = 72;
var FETCH_CONCURRENCY = 8;
function fromValue(v) {
  if (!v || typeof v !== "object") return null;
  if ("stringValue" in v) return v.stringValue;
  if ("integerValue" in v) return Number(v.integerValue);
  if ("doubleValue" in v) return v.doubleValue;
  if ("booleanValue" in v) return v.booleanValue;
  if ("nullValue" in v) return null;
  if ("timestampValue" in v) return v.timestampValue;
  if ("arrayValue" in v) return (v.arrayValue.values || []).map(fromValue);
  if ("mapValue" in v) return fromFields(v.mapValue.fields || {});
  if ("referenceValue" in v) return v.referenceValue;
  if ("geoPointValue" in v) return v.geoPointValue;
  if ("bytesValue" in v) return v.bytesValue;
  return null;
}
function fromFields(fields) {
  const out = {};
  for (const [k, v] of Object.entries(fields || {})) out[k] = fromValue(v);
  return out;
}
var cachedConfig = null;
async function firebaseConfig2(origin) {
  if (cachedConfig) return cachedConfig;
  const env = process.env;
  let projectId = env.VITE_FIREBASE_PROJECT_ID || env.FIREBASE_PROJECT_ID || "";
  let apiKey = env.VITE_FIREBASE_API_KEY || env.FIREBASE_API_KEY || "";
  if (!projectId && origin) {
    const html = await (await fetch(origin + "/")).text();
    const js = (html.match(/\/assets\/index-[^"']+\.js/) || [])[0];
    if (js) {
      const code = await (await fetch(origin + js)).text();
      projectId = projectId || (code.match(/projectId:"([^"]+)"/) || [])[1] || "";
      apiKey = apiKey || (code.match(/apiKey:"([^"]+)"/) || [])[1] || "";
    }
  }
  if (!projectId) throw new Error("Firebase project id is not configured.");
  cachedConfig = { projectId, apiKey };
  return cachedConfig;
}
async function readDoc(cfg, path) {
  const url = `https://firestore.googleapis.com/v1/projects/${cfg.projectId}/databases/(default)/documents/${path}` + (cfg.apiKey ? `?key=${cfg.apiKey}` : "");
  const res = await fetch(url);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`Firestore ${res.status} on ${path}`);
  const json = await res.json();
  return fromFields(json.fields || {});
}
async function pool(list, n, fn) {
  let i = 0;
  const run = async () => {
    while (i < list.length) {
      const k = i++;
      await fn(list[k], k);
    }
  };
  await Promise.all(Array.from({ length: Math.min(n, list.length) }, run));
}
async function loadSharedReport(shareId, { origin, readDocFn } = {}) {
  const read = readDocFn || (async (p) => readDoc(await firebaseConfig2(origin), p));
  const data = await read(`shared_reports/${shareId}`);
  if (!data) throw Object.assign(new Error("Report not found"), { status: 404 });
  const items = normalizeOpsItems(data.items || []);
  const refs = /* @__PURE__ */ new Set();
  for (const it of items) for (const p of it.photos || []) if (p && !p.url && p.photo_ref) refs.add(p.photo_ref);
  const bytes = /* @__PURE__ */ new Map();
  await pool([...refs], FETCH_CONCURRENCY, async (ref2) => {
    try {
      const d = await read(`shared_reports/${shareId}/photos/${ref2}`);
      if (d?.url) bytes.set(ref2, d.url);
    } catch (e) {
      console.warn("photo", ref2, e.message);
    }
  });
  const withBytes = items.map((it) => ({
    ...it,
    photos: (it.photos || []).map((p) => p && !p.url && p.photo_ref && bytes.has(p.photo_ref) ? { ...p, url: bytes.get(p.photo_ref) } : p)
  }));
  return { ...data, id: `share_${shareId}`, share_id: shareId, items: withBytes };
}
function nodeImageData(url) {
  try {
    return decodeAndShrink(url);
  } catch (e) {
    console.warn("image skipped:", e.message);
    return null;
  }
}
function decodeAndShrink(url) {
  const m = /^data:[^;,]*;base64,(.*)$/i.exec(String(url || ""));
  if (!m) return null;
  const raw = Buffer.from(m[1], "base64");
  let img;
  if (raw[0] === 255 && raw[1] === 216) img = jpeg.decode(raw, { useTArray: true, maxMemoryUsageInMB: 512 });
  else if (raw[0] === 137 && raw[1] === 80) {
    const png = PNG.sync.read(raw, { checkCRC: false });
    const d = png.data;
    for (let i = 0; i < d.length; i += 4) {
      const a = d[i + 3] / 255;
      d[i] = d[i] * a + 255 * (1 - a);
      d[i + 1] = d[i + 1] * a + 255 * (1 - a);
      d[i + 2] = d[i + 2] * a + 255 * (1 - a);
      d[i + 3] = 255;
    }
    img = { width: png.width, height: png.height, data: d };
  } else return null;
  const isJpeg = raw[0] === 255;
  const { width: w0, height: h0 } = img;
  const scale = Math.min(1, MAX_PX / Math.max(w0, h0));
  let out = raw;
  let w = w0;
  let h = h0;
  if (scale < 1 || !isJpeg) {
    w = Math.max(1, Math.round(w0 * scale));
    h = Math.max(1, Math.round(h0 * scale));
    const dst = new Uint8Array(w * h * 4);
    const fx = w0 / w;
    const fy = h0 / h;
    for (let y = 0; y < h; y += 1) {
      const sy0 = Math.floor(y * fy);
      const sy1 = Math.max(sy0 + 1, Math.floor((y + 1) * fy));
      for (let x = 0; x < w; x += 1) {
        const sx0 = Math.floor(x * fx);
        const sx1 = Math.max(sx0 + 1, Math.floor((x + 1) * fx));
        let r = 0;
        let g = 0;
        let b = 0;
        let n = 0;
        for (let sy = sy0; sy < sy1 && sy < h0; sy += 1) {
          let o = (sy * w0 + sx0) * 4;
          for (let sx = sx0; sx < sx1 && sx < w0; sx += 1) {
            r += img.data[o];
            g += img.data[o + 1];
            b += img.data[o + 2];
            n += 1;
            o += 4;
          }
        }
        const d = (y * w + x) * 4;
        dst[d] = r / n;
        dst[d + 1] = g / n;
        dst[d + 2] = b / n;
        dst[d + 3] = 255;
      }
    }
    out = Buffer.from(jpeg.encode({ data: dst, width: w, height: h }, QUALITY).data);
  }
  const base64 = out.toString("base64");
  return { base64, extension: "jpeg", dataUrl: `data:image/jpeg;base64,${base64}`, aspectRatio: w0 / h0, width: w, height: h };
}
var DAY2 = 864e5;
var keyToUtc2 = (k) => {
  const [y, m, d] = k.split("-").map(Number);
  return Date.UTC(y, m - 1, d);
};
var utcToKey2 = (t) => new Date(t).toISOString().slice(0, 10);
function isoWeek(key) {
  const d = new Date(keyToUtc2(key));
  const day = (d.getUTCDay() + 6) % 7;
  d.setUTCDate(d.getUTCDate() - day + 3);
  const firstThu = new Date(Date.UTC(d.getUTCFullYear(), 0, 4));
  return 1 + Math.round(((d - firstThu) / DAY2 - 3 + (firstThu.getUTCDay() + 6) % 7) / 7);
}
function weeklySummary(report, today) {
  const items = report.items || [];
  const st = opsStats(items);
  const weekAgo = utcToKey2(keyToUtc2(today) - 7 * DAY2);
  const opened = (it) => opsDateKey(it.open_date);
  const newThisWeek = items.filter((it) => opened(it) && opened(it) > weekAgo && opened(it) <= today);
  const closedThisWeek = items.filter((it) => {
    const c = closedOn(it);
    return c && c > weekAgo && c <= today;
  });
  const totalBefore = items.filter((it) => !opened(it) || opened(it) <= weekAgo).length;
  const closedBefore = items.filter((it) => {
    const c = closedOn(it);
    return normalizeOpsStatus(it.status) === OPS_STATUS.CLOSED && (!c || c <= weekAgo);
  }).length;
  const pct = (a, b) => b ? Math.round(a / b * 100) : 0;
  const split = (status) => opsActionByBreakdown(items, status).map((b) => ({ name: b.name, count: b.count, blank: b.blank }));
  return {
    title: report.title || OPS_FINDINGS_LABEL,
    location: report.location || "",
    today,
    today_label: formatOpsDate(today),
    week: isoWeek(today),
    year: Number(today.slice(0, 4)),
    totals: { total: st.total, open: st.open, ongoing: st.ongoing, closed: st.closed, percentClosed: st.percentClosed },
    actionBy: { total: split(""), open: split(OPS_STATUS.OPEN), ongoing: split(OPS_STATUS.ONGOING), closed: split(OPS_STATUS.CLOSED) },
    sections: opsSectionSummary(items).map((s) => ({ section: s.section, letter: s.letter, ...s.stats })),
    thisWeek: { new: newThisWeek.length, closed: closedThisWeek.length, percentNow: st.percentClosed, percentLastWeek: pct(closedBefore, totalBefore) },
    nyClarify: items.filter((it) => !String(it.action_by || "").trim()).length
  };
}
var esc = (t) => String(t ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
var DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
var MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
var longDate = (k) => {
  const d = new Date(keyToUtc2(k));
  return `${String(d.getUTCDate()).padStart(2, "0")}-${MON[d.getUTCMonth()]}-${d.getUTCFullYear()}`;
};
function nextMeetingDay(today, dayName) {
  const want = Math.max(0, DAYS.findIndex((d) => d.toLowerCase() === String(dayName || "tuesday").toLowerCase()));
  const t = keyToUtc2(today);
  const cur = new Date(t).getUTCDay();
  const add = (want - cur + 7) % 7 || 7;
  return utcToKey2(t + add * DAY2);
}
function emailOptions(q = {}) {
  const pick = (k, d) => q[k] !== void 0 && String(q[k]).trim() !== "" ? String(q[k]).slice(0, 300) : d;
  return {
    project: pick("project", "Block B - EPC#1"),
    meetDay: pick("meetday", "Tuesday"),
    meetStart: pick("meetstart", "09:00"),
    meetMinutes: Number(pick("meetmin", "60")) || 60,
    venue: pick("venue", "Site office meeting room / Microsoft Teams"),
    agenda: pick("agenda", "1) New findings this week  2) Open items per Action By  3) Items to be clarified (NY Clarify)  4) Close-out evidence"),
    sender: pick("sender", "Vu Ba Dien"),
    senderTitle: pick("title", "Bureau Veritas - Block B EPC#1"),
    link: pick("link", "https://flash-report-pro.vercel.app/#/OPS-Finding-Status")
  };
}
function emailSubject(sum, o) {
  return `${o.project} - [OPS Findings] Weekly Status Report & Weekly Meeting - Week ${String(sum.week).padStart(2, "0")} (${longDate(sum.today)})`;
}
function emailHtml(sum, o, nowLabel = "") {
  const t = sum.totals;
  const pc = (v) => t.total ? Math.round(100 * v / t.total) : 0;
  const chips = (list) => (list || []).map((b) => `<span style="${b.blank ? "color:#92400e;" : ""}">${esc(b.name)} ${b.count}</span>`).join(" &middot; ");
  const tile = (label, value, pct, color, list) => `<td width="25%" style="border:1px solid #d7dee8;padding:10px;vertical-align:top;"><div style="font-size:11px;color:#64748b;font-weight:bold;">${label}</div><div style="font-size:24px;font-weight:bold;color:${color};">${value}${pct === null ? "" : ` <span style="font-size:12px;color:#64748b;">${pct}%</span>`}</div><div style="font-size:11px;color:#475569;">${chips(list)}</div></td>`;
  const td = 'style="padding:6px 8px;border:1px solid #d7dee8;"';
  const tdc = 'align="center" style="padding:6px 8px;border:1px solid #d7dee8;"';
  const rows = sum.sections.map((s) => `<tr><td ${td}>${esc(s.section)}</td><td ${tdc}>${s.total}</td><td ${tdc}><span style="color:#b91c1c;">${s.open}</span></td><td ${tdc}>${s.ongoing}</td><td ${tdc}><span style="color:#047857;">${s.closed}</span></td><td ${tdc}>${s.percentClosed}%</td></tr>`).join("") + `<tr style="background:#f1f5f9;font-weight:bold;"><td ${td}>Total</td><td ${tdc}>${t.total}</td><td ${tdc}>${t.open}</td><td ${tdc}>${t.ongoing}</td><td ${tdc}>${t.closed}</td><td ${tdc}>${t.percentClosed}%</td></tr>`;
  const mDay = nextMeetingDay(sum.today, o.meetDay);
  const [hh, mm] = String(o.meetStart).split(":").map((x) => Number(x) || 0);
  const endMin = hh * 60 + mm + o.meetMinutes;
  const hm = (m) => `${String(Math.floor(m / 60) % 24).padStart(2, "0")}:${String(m % 60).padStart(2, "0")}`;
  const mLabel = `${DAYS[new Date(keyToUtc2(mDay)).getUTCDay()]}, ${longDate(mDay)}, ${hm(hh * 60 + mm)} - ${hm(endMin)}`;
  const w = sum.thisWeek;
  const ny = sum.nyClarify > 0 ? `<tr><td style="padding:10px 24px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#fffbeb;border:1px solid #fcd34d;"><tr><td style="padding:10px 14px;font-size:13px;line-height:1.55;"><b>Action requested:</b> <b>${sum.nyClarify}</b> findings have no Action By yet (<b>NY Clarify</b>). Please confirm the responsible party (CONS / PE) before or during the meeting. Action parties are kindly requested to update status and close-out evidence directly in the live register.</td></tr></table></td></tr>` : "";
  return `<html><body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;color:#1e293b;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:760px;border:1px solid #d7dee8;">
<tr><td style="background:#1F3A5F;padding:18px 24px;">
<div style="font-size:12px;color:#aac4e6;letter-spacing:1px;">${esc(o.project.toUpperCase())} &middot; ${esc(sum.location)}</div>
<div style="font-size:20px;font-weight:bold;color:#ffffff;margin-top:4px;">OPS Findings &amp; Action Tracking &ndash; Weekly Status</div>
<div style="font-size:13px;color:#d6e2f2;margin-top:2px;">Week ${String(sum.week).padStart(2, "0")} &middot; status as of ${longDate(sum.today)}${nowLabel ? ` ${nowLabel}` : ""}</div>
</td></tr>
<tr><td style="padding:20px 24px 4px 24px;font-size:14px;line-height:1.55;">Dear All,<br><br>Please find attached the weekly status of the OPS Findings &amp; Action Tracking (Excel and PDF). The figures below are taken from the live register at the time of sending. We will review the open items together at the weekly meeting below.</td></tr>
<tr><td style="padding:12px 24px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f0f7ff;border:1px solid #bcd6f5;"><tr><td style="padding:12px 16px;font-size:14px;line-height:1.6;">
<div style="font-weight:bold;color:#1F3A5F;font-size:15px;margin-bottom:4px;">&#128197; Weekly OPS Findings Meeting</div>
<b>Date / time:</b> ${esc(mLabel)}<br><b>Venue:</b> ${esc(o.venue)}<br><b>Agenda:</b> ${esc(o.agenda)}
</td></tr></table></td></tr>
<tr><td style="padding:8px 24px 4px 24px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="6"><tr>${tile("TOTAL FINDINGS", t.total, null, "#1e293b", sum.actionBy.total)}${tile("OPEN", t.open, pc(t.open), "#b91c1c", sum.actionBy.open)}${tile("ON-GOING", t.ongoing, pc(t.ongoing), "#b45309", sum.actionBy.ongoing)}${tile("CLOSED", t.closed, pc(t.closed), "#047857", sum.actionBy.closed)}</tr></table></td></tr>
<tr><td style="padding:8px 24px;font-size:13px;"><b>This week:</b> +<b>${w.new}</b> new findings &middot; <b>${w.closed}</b> closed &middot; close-out progress <b>${w.percentNow}%</b> (last week ${w.percentLastWeek}%)</td></tr>
<tr><td style="padding:4px 24px 8px 24px;"><div style="font-size:14px;font-weight:bold;color:#1F3A5F;margin-bottom:6px;">Status by section</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:13px;">
<tr style="background:#1F3A5F;color:#ffffff;"><td style="padding:7px 8px;">Section</td><td align="center">Total</td><td align="center">Open</td><td align="center">On-going</td><td align="center">Closed</td><td align="center">% Closed</td></tr>
${rows}
</table></td></tr>
${ny}
<tr><td align="center" style="padding:10px 24px 18px 24px;"><a href="${esc(o.link)}" style="display:inline-block;background:#0369a1;color:#ffffff;text-decoration:none;font-weight:bold;font-size:14px;padding:10px 22px;">Open the live OPS Finding Status</a>
<div style="font-size:11px;color:#64748b;margin-top:6px;">View, filter and export without a password &middot; editing requires the section password</div></td></tr>
<tr><td style="padding:4px 24px 20px 24px;font-size:13px;line-height:1.55;border-top:1px solid #e2e8f0;"><br>Best regards,<br><b>${esc(o.sender)}</b><br>${esc(o.senderTitle)}<br>
<span style="font-size:11px;color:#94a3b8;">This e-mail is generated automatically every week from the OPS Findings register. Please reply to this e-mail for any question.</span></td></tr>
</table></body></html>`;
}
function todayVN() {
  return new Date(Date.now() + 7 * 36e5).toISOString().slice(0, 10);
}
async function handler(req, res) {
  const q = req.query || {};
  const shareId = String(q.share || "").replace(/[^A-Za-z0-9_-]/g, "");
  const format = String(q.format || "json").toLowerCase();
  if (!shareId) {
    res.status(400).json({ error: "share is required" });
    return;
  }
  try {
    const origin = `https://${req.headers["x-forwarded-host"] || req.headers.host}`;
    const report = await loadSharedReport(shareId, { origin });
    const today = todayVN();
    const sum = weeklySummary(report, today);
    const base = `OPS_Findings_Week${String(sum.week).padStart(2, "0")}_${today}`;
    res.setHeader("Cache-Control", "no-store");
    if (format === "json") {
      res.status(200).json(sum);
      return;
    }
    if (format === "html" || format === "subject") {
      const o = emailOptions(q);
      const hhmm = new Date(Date.now() + 7 * 36e5).toISOString().slice(11, 16);
      const text = format === "html" ? emailHtml(sum, o, hhmm) : emailSubject(sum, o);
      res.setHeader("Content-Type", format === "html" ? "text/html; charset=utf-8" : "text/plain; charset=utf-8");
      res.status(200).send(text);
      return;
    }
    setImageLoader(nodeImageData);
    const out = format === "pdf" ? await exportOpsPdf(report, null, { returnBuffer: true, fileName: base }) : await exportOpsExcel(report, null, { returnBuffer: true, fileName: base });
    const buf = Buffer.from(out.buffer);
    res.setHeader("Content-Type", format === "pdf" ? "application/pdf" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="${out.fileName}"`);
    res.setHeader("Content-Length", String(buf.length));
    res.status(200).send(buf);
  } catch (e) {
    console.error("ops-weekly", e);
    res.status(e.status || 500).json({ error: e.message || String(e) });
  }
}
export {
  handler as default,
  emailHtml,
  emailOptions,
  emailSubject,
  fromFields,
  isoWeek,
  loadSharedReport,
  nextMeetingDay,
  nodeImageData,
  weeklySummary
};
